import 'package:flutter/material.dart';
import 'app_theme.dart';

/// ========== 主题1: Glassmorphism 赛博霓虹 ==========
final AppTheme glassmorphism = AppTheme(
  style: ThemeStyle.glassmorphism,
  name: '赛博霓虹',
  description: 'Glassmorphism 3.0风格，霓虹光效与毛玻璃质感',
  background: const Color(0xFF0A0A0F),
  surface: const Color(0xFF12121A),
  primary: const Color(0xFF00F0FF),
  secondary: const Color(0xFFB829F7),
  accent: const Color(0xFFFF2E8C),
  textPrimary: Colors.white,
  textSecondary: const Color(0xFFB0B0C0),
  textTertiary: const Color(0xFF707080),
  success: const Color(0xFF00E676),
  warning: const Color(0xFFFF9100),
  error: const Color(0xFFFF2E8C),
  info: const Color(0xFF2979FF),
  gradientPrimary: [const Color(0xFF00F0FF), const Color(0xFFB829F7)],
  gradientAccent: [const Color(0xFFFF2E8C), const Color(0xFF2979FF)],
  radiusSmall: 12,
  radiusMedium: 20,
  radiusLarge: 28,
  shadows: [
    BoxShadow(color: const Color(0xFF00F0FF).withValues(alpha: 0.3), blurRadius: 20, spreadRadius: -5),
  ],
  useGlassmorphism: true,
  useGlow: true,
  useNeon: true,
  glassOpacity: 0.12,
  blurAmount: 20,
);

/// ========== 主题2: Minimal Zen 极简禅意 ==========
final AppTheme minimalZen = AppTheme(
  style: ThemeStyle.minimalZen,
  name: '极简禅意',
  description: '日式极简美学，留白与克制',
  background: const Color(0xFFFAFAF8),
  surface: Colors.white,
  primary: const Color(0xFF2C2C2C),
  secondary: const Color(0xFF8B8B8B),
  accent: const Color(0xFFE85D4E),
  textPrimary: const Color(0xFF1A1A1A),
  textSecondary: const Color(0xFF666666),
  textTertiary: const Color(0xFF999999),
  success: const Color(0xFF4A7C59),
  warning: const Color(0xFFD4A373),
  error: const Color(0xFFE85D4E),
  info: const Color(0xFF6B8E9F),
  gradientPrimary: [const Color(0xFF2C2C2C), const Color(0xFF4A4A4A)],
  gradientAccent: [const Color(0xFFE85D4E), const Color(0xFFF4A261)],
  radiusSmall: 4,
  radiusMedium: 8,
  radiusLarge: 12,
  shadows: [
    BoxShadow(color: Colors.black.withValues(alpha: 0.06), blurRadius: 12, offset: const Offset(0, 2)),
  ],
);

/// ========== 主题3: Nature Organic 自然有机 ==========
final AppTheme natureOrganic = AppTheme(
  style: ThemeStyle.natureOrganic,
  name: '自然有机',
  description: '大地色系，有机曲线与自然灵感',
  background: const Color(0xFFF5F1EB),
  surface: const Color(0xFFFAF8F5),
  primary: const Color(0xFF2D5A4A),
  secondary: const Color(0xFF8B6F4E),
  accent: const Color(0xFFD4A574),
  textPrimary: const Color(0xFF2C2416),
  textSecondary: const Color(0xFF5C4D3C),
  textTertiary: const Color(0xFF8B7D6B),
  success: const Color(0xFF5A8F6E),
  warning: const Color(0xFFE6A94E),
  error: const Color(0xFFC75B4B),
  info: const Color(0xFF5A7A8C),
  gradientPrimary: [const Color(0xFF2D5A4A), const Color(0xFF4A7C6F)],
  gradientAccent: [const Color(0xFFD4A574), const Color(0xFFE8C9A0)],
  radiusSmall: 16,
  radiusMedium: 24,
  radiusLarge: 32,
  shadows: [
    BoxShadow(color: const Color(0xFF2D5A4A).withValues(alpha: 0.1), blurRadius: 16, offset: const Offset(0, 4)),
  ],
);

/// ========== 主题4: Retro Wave 复古蒸汽波 ==========
final AppTheme retroWave = AppTheme(
  style: ThemeStyle.retroWave,
  name: '复古蒸汽波',
  description: '80年代复古美学，粉色日落与霓虹网格',
  background: const Color(0xFF1A0B2E),
  surface: const Color(0xFF2D1B4E),
  primary: const Color(0xFFFF71CE),
  secondary: const Color(0xFF01CDFE),
  accent: const Color(0xFF05FFA1),
  textPrimary: const Color(0xFFFFE4F8),
  textSecondary: const Color(0xFFB8A1C9),
  textTertiary: const Color(0xFF7A6B8A),
  success: const Color(0xFF05FFA1),
  warning: const Color(0xFFFFE600),
  error: const Color(0xFFFF3864),
  info: const Color(0xFF01CDFE),
  gradientPrimary: [const Color(0xFFFF71CE), const Color(0xFF01CDFE)],
  gradientAccent: [const Color(0xFFFF71CE), const Color(0xFFFF3864)],
  radiusSmall: 0,
  radiusMedium: 4,
  radiusLarge: 8,
  shadows: [
    BoxShadow(color: const Color(0xFFFF71CE).withValues(alpha: 0.5), blurRadius: 20, spreadRadius: 2),
  ],
  useGlow: true,
  useNeon: true,
);

/// ========== 主题5: Corporate Pro 商务专业 ==========
final AppTheme corporatePro = AppTheme(
  style: ThemeStyle.corporatePro,
  name: '商务专业',
  description: '深蓝商务风格，专业可信赖',
  background: const Color(0xFF0F172A),
  surface: const Color(0xFF1E293B),
  primary: const Color(0xFF3B82F6),
  secondary: const Color(0xFF64748B),
  accent: const Color(0xFF10B981),
  textPrimary: const Color(0xFFF1F5F9),
  textSecondary: const Color(0xFF94A3B8),
  textTertiary: const Color(0xFF64748B),
  success: const Color(0xFF10B981),
  warning: const Color(0xFFF59E0B),
  error: const Color(0xFFEF4444),
  info: const Color(0xFF3B82F6),
  gradientPrimary: [const Color(0xFF3B82F6), const Color(0xFF1D4ED8)],
  gradientAccent: [const Color(0xFF10B981), const Color(0xFF059669)],
  radiusSmall: 6,
  radiusMedium: 10,
  radiusLarge: 14,
  shadows: [
    BoxShadow(color: Colors.black.withValues(alpha: 0.3), blurRadius: 12, offset: const Offset(0, 4)),
  ],
);
